In [4]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
from sklearn.model_selection import cross_val_score

In [5]:
df = pd.read_csv("Data_for_UCI_named.csv")

In [6]:
df.head(3)

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable

In [7]:
df.isna().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [8]:
df['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [9]:
df.describe(include='all').head()

tau1          tau2          tau3          tau4        p1  \
count   10000.00  10000.000000  10000.000000  10000.000000  10000.00   
unique       NaN           NaN           NaN           NaN       NaN   
top          NaN           NaN           NaN           NaN       NaN   
freq         NaN           NaN           NaN           NaN       NaN   
mean        5.25      5.250001      5.250004      5.249997      3.75   

              p2        p3        p4         g1         g2         g3  \
count   10000.00  10000.00  10000.00  10000.000  10000.000  10000.000   
unique       NaN       NaN       NaN        NaN        NaN        NaN   
top          NaN       NaN       NaN        NaN        NaN        NaN   
freq         NaN       NaN       NaN        NaN        NaN        NaN   
mean       -1.25     -1.25     -1.25      0.525      0.525      0.525   

               g4          stab     stabf  
count   10000.000  10000.000000     10000  
unique        NaN           NaN         2  
top           NaN           NaN  unstable  
freq          NaN           NaN      6380  
mean        0.525      0.015731       NaN

In [10]:
df = df.drop(columns='stab')

In [11]:
df.head(3)

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   

         p4        g1        g2        g3        g4     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  unstable

In [13]:
x = df.drop(columns='stabf')
y = df['stabf']

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
y_train.value_counts()

unstable    5092
stable      2908
Name: stabf, dtype: int64

In [15]:
#encode categorical variable
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [ ]:
#y_train_ = encoder.fit_transform(y_train)

In [26]:
from sklearn import metrics

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [17]:
scaled_train_df = scaler.fit_transform(x_train)
scaled_train_df = pd.DataFrame(scaled_train_df,columns=x_train.columns)

In [18]:
x_test = x_test.reset_index(drop=True)
scaled_test_df = scaler.transform(x_test)
scaled_test_df = pd.DataFrame(scaled_test_df,columns=x_test.columns)

Random Forest

In [19]:
from sklearn.ensemble import RandomForestClassifier
rdf = RandomForestClassifier(random_state=1)

In [20]:
rdf_classify = rdf.fit(scaled_train_df,y_train)

In [21]:
new_predictions = rdf_classify.predict(scaled_test_df)

In [24]:
accuracy = accuracy_score(y_true=y_test, y_pred=new_predictions)
#print('Accuracy: {}'.format(round(accuracy*100), 2))
round(accuracy,4)

0.929

In [27]:
print(metrics.classification_report(y_test,new_predictions))

              precision    recall  f1-score   support

      stable       0.92      0.88      0.90       712
    unstable       0.93      0.96      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [28]:
confusion_matrix(y_true=y_test, y_pred=new_predictions, labels=['unstable', 'stable'])

array([[1233,   55],
       [  87,  625]])

ExtraTree Classfier

In [29]:
from sklearn.ensemble import ExtraTreesClassifier
exclf = ExtraTreesClassifier(random_state=1)

In [30]:
extra_tree = exclf.fit(scaled_train_df,y_train)

In [31]:
extra_predictions = extra_tree.predict(scaled_test_df)

In [34]:
extra_accuracy = accuracy_score(y_true=y_test, y_pred=extra_predictions)
#print('Accuracy: {}'.format(round(accuracy,4), 4))

Accuracy: 0.929


In [35]:
print(metrics.classification_report(y_test,extra_predictions))

              precision    recall  f1-score   support

      stable       0.94      0.85      0.89       712
    unstable       0.92      0.97      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [36]:
confusion_matrix(y_true=y_test, y_pred=extra_predictions, labels=['unstable', 'stable'])

array([[1250,   38],
       [ 106,  606]])

In [66]:
feature_importance = extra_tree.feature_importances_
feature_importance

array([0.11739736, 0.11844468, 0.11316851, 0.11546569, 0.03950675,
       0.04037132, 0.04070628, 0.04057864, 0.08978291, 0.09367636,
       0.09688268, 0.09401882])

XGBoost Classifier

In [37]:
from xgboost import XGBClassifier
xgc = XGBClassifier(random_state=1)

In [38]:
xclf = xgc.fit(scaled_train_df, y_train)
y_pred = xgc.predict(scaled_test_df)

In [40]:
xgb_accuracy = accuracy_score(y_true=y_test, y_pred=y_pred)
#print('Accuracy: {}'.format(round(accuracy*100), 2))
round(xgb_accuracy,4) 

0.9455

In [ ]:
#xclf.score(scaled_train_df, y_train)
#xclf.score(scaled_test_df, y_test)

In [41]:
xgf1 = f1_score(y_true=y_test, y_pred=y_pred, pos_label='stable')
print('F1: {}'.format(round(xgf1*100), 2))

F1: 92


In [42]:
xgcnf_mat = confusion_matrix(y_true=y_test, y_pred=y_pred, labels=['stable', 'unstable'])
xgcnf_mat

array([[ 648,   64],
       [  45, 1243]])

In [43]:
print(metrics.classification_report(y_test,y_pred))

              precision    recall  f1-score   support

      stable       0.94      0.91      0.92       712
    unstable       0.95      0.97      0.96      1288

    accuracy                           0.95      2000
   macro avg       0.94      0.94      0.94      2000
weighted avg       0.95      0.95      0.95      2000



In [44]:
confusion_matrix(y_true=y_test, y_pred=y_pred, labels=['unstable', 'stable'])

array([[1243,   45],
       [  64,  648]])

Light Gradient Boosting Model

In [45]:
import lightgbm as lgb
lgc = lgb.LGBMClassifier()

In [46]:
lgbm = lgc.fit(scaled_train_df, y_train)
y_hat = lgbm.predict(scaled_test_df)

In [47]:
lgb_accuracy = accuracy_score(y_true=y_test, y_pred=y_hat)
#print('Accuracy: {}'.format(round(accuracy*100), 2))

Accuracy: 93


In [48]:
lgb_accuracy

0.9395

In [86]:
lgf1 = f1_score(y_true=y_test, y_pred=y_hat, pos_label='unstable')
print('F1: {}'.format(round(lgf1*100), 2))

F1: 95


In [97]:
print(metrics.classification_report(y_test,y_hat))

              precision    recall  f1-score   support

      stable       0.93      0.90      0.91       712
    unstable       0.95      0.96      0.95      1288

    accuracy                           0.94      2000
   macro avg       0.94      0.93      0.93      2000
weighted avg       0.94      0.94      0.94      2000



In [105]:
confusion_matrix(y_true=y_test, y_pred=y_hat, labels=['unstable', 'stable'])

array([[1238,   50],
       [  71,  641]])

Randomized SearchCV

In [49]:
from sklearn.model_selection import RandomizedSearchCV

In [51]:
n_estimators = [50,100,300,500,1000]
min_samples_split = [2,3,5,7,9]
min_samples_leaf = [1,2,4,6,8]
max_features = ['auto','sqrt','log2',None]
hyperparamter_grid = {'n_estimators':n_estimators,'min_samples_split':min_samples_split,'min_samples_leaf':min_samples_leaf,'max_features':max_features}

In [52]:
clf = RandomizedSearchCV(exclf,hyperparamter_grid,n_iter=10,scoring='accuracy',n_jobs = -1, verbose = 1,cv=3,random_state=1)
model = clf.fit(scaled_train_df, y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits


In [53]:
from pprint import pprint
pprint(model.best_estimator_.get_params())

{'bootstrap': False,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 8,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 1000,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 1,
 'verbose': 0,
 'warm_start': False}


In [55]:
predictions = model.predict(scaled_test_df)
accuracy = accuracy_score(y_true=y_test, y_pred=predictions)
#print('Accuracy: {}'.format(round(accuracy*100), 2))
round(accuracy,4)

0.927

In [96]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

      stable       0.92      0.87      0.89       712
    unstable       0.93      0.96      0.94      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [104]:
confusion_matrix(y_true=y_test, y_pred=predictions, labels=['unstable', 'stable'])

array([[1235,   53],
       [  93,  619]])